// =============================================================
// SonicTemple Planner — js/data.js
// AUTO-GENERATED by scripts/sync-sheet.js
// Last synced: 2026-04-15T18:42:53.335Z
// =============================================================

const GENERATED_AT = "2026-04-15T18:42:53.335Z";
const SHEET_SOURCE  = "https://docs.google.com/spreadsheets/d/1_mlpVRSg7sCzwaba81_7cEW-iUskwLL5x8Ak8rUnWRI";

const FRIENDS = [
  { id: 'friend1', name: 'DK',   color: '#e74c3c' },
  { id: 'friend2', name: 'MG',   color: '#3498db' },
  { id: 'friend3', name: 'Abel', color: '#2ecc71' },
  { id: 'friend4', name: 'Friend4', color: '#f39c12' },
  { id: 'friend5', name: 'Friend5', color: '#9b59b6' },
  { id: 'friend6', name: 'Friend6', color: '#1abc9c' },
  { id: 'friend7', name: 'Friend7', color: '#e91e63' },
];

const STAGES = [
  { id: 'temple',    name: 'Temple',    color: '#cc0000' },
  { id: 'cathedral', name: 'Cathedral', color: '#1a6b3c' },
  { id: 'citadel',   name: 'Citadel',   color: '#1a3a6b' },
  { id: 'sanctuary', name: 'Sanctuary', color: '#6b1a6b' },
  { id: 'altar',     name: 'Altar',     color: '#8b5e3c' },
];

const DAYS = [
  { id: 'thursday', label: 'Thu · May 14', date: '2026-05-14' },
  { id: 'friday',   label: 'Fri · May 15', date: '2026-05-15' },
  { id: 'saturday', label: 'Sat · May 16', date: '2026-05-16' },
  { id: 'sunday',   label: 'Sun · May 17', date: '2026-05-17' },
];

const SCHEDULE = [

];
